//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResinTimer.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResinTimer.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Caution과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountCautionPage_SubTitle {
            get {
                return ResourceManager.GetString("AccountCautionPage_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Caution과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountCautionPage_Title {
            get {
                return ResourceManager.GetString("AccountCautionPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Cookie (Auto)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountCookieInputAutoPage_Title {
            get {
                return ResourceManager.GetString("AccountCookieInputAutoPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Cookie (Manual)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountCookieInputManualPage_Title {
            get {
                return ResourceManager.GetString("AccountCookieInputManualPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Cookie과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountCookieInputPage_Title {
            get {
                return ResourceManager.GetString("AccountCookieInputPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account information is important personal information. Thus, this app will never collect it, and it will only be stored on your device.
        ///
        ///Users can delete the information at any time, and please note that we are not responsible for any disadvantages caused by using the function, except in cases where the app bug.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSetting_Caution_Message {
            get {
                return ResourceManager.GetString("AccountSetting_Caution_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success to set account info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSetting_Complete {
            get {
                return ResourceManager.GetString("AccountSetting_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSetting_CookieInputMethod_Auto {
            get {
                return ResourceManager.GetString("AccountSetting_CookieInputMethod_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose how to set cookie information.
        ///
        ///Auto: After logging in from the Hoyolab attendance check page, click the Apply button in the upper right corner to recognize and set cookies
        ///
        ///Manual: Enter cookie information (ltuid, ltoken values) directly과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSetting_CookieInputMethod_Description {
            get {
                return ResourceManager.GetString("AccountSetting_CookieInputMethod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSetting_CookieInputMethod_Manual {
            get {
                return ResourceManager.GetString("AccountSetting_CookieInputMethod_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to set cookie info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSetting_SetCookieInfo_Fail {
            get {
                return ResourceManager.GetString("AccountSetting_SetCookieInfo_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success to set cookie info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSetting_SetCookieInfo_Success {
            get {
                return ResourceManager.GetString("AccountSetting_SetCookieInfo_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Config Feature과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSyncConfig_ConfigSection_Title {
            get {
                return ResourceManager.GetString("AccountSyncConfig_ConfigSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync Config과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSyncConfigPage_Title {
            get {
                return ResourceManager.GetString("AccountSyncConfigPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSyncStatus_Checking {
            get {
                return ResourceManager.GetString("AccountSyncStatus_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSyncStatus_Connected {
            get {
                return ResourceManager.GetString("AccountSyncStatus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSyncStatus_Disabled {
            get {
                return ResourceManager.GetString("AccountSyncStatus_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSyncStatus_Disconnected {
            get {
                return ResourceManager.GetString("AccountSyncStatus_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot receive data from server with this account.
        ///You can renew account to solve this problem.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSyncStatusPage_Disconnected_Tip {
            get {
                return ResourceManager.GetString("AccountSyncStatusPage_Disconnected_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Real-Time Note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSyncStatusPage_EnableDailyNote_Button {
            get {
                return ResourceManager.GetString("AccountSyncStatusPage_EnableDailyNote_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to enable real-time note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSyncStatusPage_EnableDailyNote_Fail {
            get {
                return ResourceManager.GetString("AccountSyncStatusPage_EnableDailyNote_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success to enable real-time note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSyncStatusPage_EnableDailyNote_Success {
            get {
                return ResourceManager.GetString("AccountSyncStatusPage_EnableDailyNote_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSyncStatusPage_RemoveAccount_Button {
            get {
                return ResourceManager.GetString("AccountSyncStatusPage_RemoveAccount_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove account fail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSyncStatusPage_RemoveAccount_Fail {
            get {
                return ResourceManager.GetString("AccountSyncStatusPage_RemoveAccount_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove account success과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSyncStatusPage_RemoveAccount_Success {
            get {
                return ResourceManager.GetString("AccountSyncStatusPage_RemoveAccount_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renew과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSyncStatusPage_RenewAccount_Button {
            get {
                return ResourceManager.GetString("AccountSyncStatusPage_RenewAccount_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSyncStatusPage_Title {
            get {
                return ResourceManager.GetString("AccountSyncStatusPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input UID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountUIDInputPage_SubTitle {
            get {
                return ResourceManager.GetString("AccountUIDInputPage_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input UID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountUIDInputPage_Title {
            get {
                return ResourceManager.GetString("AccountUIDInputPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expedition과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppAction_App_Timer_Expedition {
            get {
                return ResourceManager.GetString("AppAction_App_Timer_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Furnishing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppAction_App_Timer_Furnishing {
            get {
                return ResourceManager.GetString("AppAction_App_Timer_Furnishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gadget과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppAction_App_Timer_Gadget {
            get {
                return ResourceManager.GetString("AppAction_App_Timer_Gadget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gardening과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppAction_App_Timer_Gardening {
            get {
                return ResourceManager.GetString("AppAction_App_Timer_Gardening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppAction_App_Timer_GatheringItem {
            get {
                return ResourceManager.GetString("AppAction_App_Timer_GatheringItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm Currency과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppAction_App_Timer_RealmCurrency {
            get {
                return ResourceManager.GetString("AppAction_App_Timer_RealmCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm Friendship과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppAction_App_Timer_RealmFriendship {
            get {
                return ResourceManager.GetString("AppAction_App_Timer_RealmFriendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppAction_App_Timer_Resin {
            get {
                return ResourceManager.GetString("AppAction_App_Timer_Resin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Talent과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppAction_App_Timer_Talent {
            get {
                return ResourceManager.GetString("AppAction_App_Timer_Talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weapon Asc.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppAction_App_Timer_WA {
            get {
                return ResourceManager.GetString("AppAction_App_Timer_WA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin alarm register fail
        ///Please re-enable alarm in app setting to register notification alarm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BootAlarmRegisterFail {
            get {
                return ResourceManager.GetString("BootAlarmRegisterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin alarm register success과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BootAlarmRegisterSuccess {
            get {
                return ResourceManager.GetString("BootAlarmRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you want to register resin notification automatically, you must enable startup property. Open Windows Task Manager and select &apos;Startup&apos;. Then, enable &apos;ResinTimer Bootstrap&apos; item.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bootstrap_ChangeEnableFail_Message {
            get {
                return ResourceManager.GetString("Bootstrap_ChangeEnableFail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StartUp Enable Process Fail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bootstrap_ChangeEnableFail_Title {
            get {
                return ResourceManager.GetString("Bootstrap_ChangeEnableFail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simple Edit Bounty과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BountySimpleEditDialog_Title {
            get {
                return ResourceManager.GetString("BountySimpleEditDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you report bug via github, you need github account. If you don&apos;t want to create github account, cancel this dialog and use E-Mail for bug reporting. Do you want to continue this process?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BugReport_Dialog_Message {
            get {
                return ResourceManager.GetString("BugReport_Dialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Caution과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BugReport_Dialog_Title {
            get {
                return ResourceManager.GetString("BugReport_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input only resin can cause time inaccuracy x~x과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Caution_ResinInput {
            get {
                return ResourceManager.GetString("Caution_ResinInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Checklist_Type_Custom {
            get {
                return ResourceManager.GetString("Checklist_Type_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daily과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Checklist_Type_Daily {
            get {
                return ResourceManager.GetString("Checklist_Type_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monthly과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Checklist_Type_Monthly {
            get {
                return ResourceManager.GetString("Checklist_Type_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Once과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Checklist_Type_Once {
            get {
                return ResourceManager.GetString("Checklist_Type_Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weekly과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Checklist_Type_Weekly {
            get {
                return ResourceManager.GetString("Checklist_Type_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simple Edit Currency과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrencySimpleEditDialog_Title {
            get {
                return ResourceManager.GetString("CurrencySimpleEditDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Agree과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dialog_Agree {
            get {
                return ResourceManager.GetString("Dialog_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dialog_Apply {
            get {
                return ResourceManager.GetString("Dialog_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disagree과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dialog_Disagree {
            get {
                return ResourceManager.GetString("Dialog_Disagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dialog_No {
            get {
                return ResourceManager.GetString("Dialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ok과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dialog_Ok {
            get {
                return ResourceManager.GetString("Dialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dialog_Yes {
            get {
                return ResourceManager.GetString("Dialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditExpedition_SelectTime {
            get {
                return ResourceManager.GetString("EditExpedition_SelectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditExpedition_SelectType {
            get {
                return ResourceManager.GetString("EditExpedition_SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   25% time reduction과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditExpedition_TimeEffectOption {
            get {
                return ResourceManager.GetString("EditExpedition_TimeEffectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Expedition과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditExpedition_Title_Edit {
            get {
                return ResourceManager.GetString("EditExpedition_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Expedition과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditExpedition_Title_New {
            get {
                return ResourceManager.GetString("EditExpedition_Title_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item Note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditItemPage_Note {
            get {
                return ResourceManager.GetString("EditItemPage_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Optional)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditItemPage_Note_Placeholder {
            get {
                return ResourceManager.GetString("EditItemPage_Note_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditItemPage_SelectType {
            get {
                return ResourceManager.GetString("EditItemPage_SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditItemPage_Title_Edit {
            get {
                return ResourceManager.GetString("EditItemPage_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditItemPage_Title_New {
            get {
                return ResourceManager.GetString("EditItemPage_Title_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditPage_ApplyButtonText {
            get {
                return ResourceManager.GetString("EditPage_ApplyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hour과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditPage_Hour {
            get {
                return ResourceManager.GetString("EditPage_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditPage_Minute {
            get {
                return ResourceManager.GetString("EditPage_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now resin count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditPage_NowResinLabel {
            get {
                return ResourceManager.GetString("EditPage_NowResinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sec과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditPage_Second {
            get {
                return ResourceManager.GetString("EditPage_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditPage_TabResin_Title {
            get {
                return ResourceManager.GetString("EditPage_TabResin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditPage_TabTime_Title {
            get {
                return ResourceManager.GetString("EditPage_TabTime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditPage_Title {
            get {
                return ResourceManager.GetString("EditPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remain Total Restore Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditPage_TotalRemainTimeLabel {
            get {
                return ResourceManager.GetString("EditPage_TotalRemainTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditRealmCurrencySetting_Title {
            get {
                return ResourceManager.GetString("EditRealmCurrencySetting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_Complete {
            get {
                return ResourceManager.GetString("Expedition_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chunk과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_Type_Chunk {
            get {
                return ResourceManager.GetString("Expedition_Type_Chunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ingredient과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_Type_Ingredient {
            get {
                return ResourceManager.GetString("Expedition_Type_Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mora과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_Type_Mora {
            get {
                return ResourceManager.GetString("Expedition_Type_Mora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expedition과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExpeditionMain_Title {
            get {
                return ResourceManager.GetString("ExpeditionMain_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remain과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExpeditionTimerPage_Remain {
            get {
                return ResourceManager.GetString("ExpeditionTimerPage_Remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ★★ Furnish과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Furnishing_Rarity_2 {
            get {
                return ResourceManager.GetString("Furnishing_Rarity_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ★★★ Furnish과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Furnishing_Rarity_3 {
            get {
                return ResourceManager.GetString("Furnishing_Rarity_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ★★★★ Furnish과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Furnishing_Rarity_4 {
            get {
                return ResourceManager.GetString("Furnishing_Rarity_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finished과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FurnishingItemTimer_Complete {
            get {
                return ResourceManager.GetString("FurnishingItemTimer_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Furnishing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FurnishingTimerPage_Title {
            get {
                return ResourceManager.GetString("FurnishingTimerPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speed Up (-4H)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FurnishingTimerPage_Toolbar_SpeedUp {
            get {
                return ResourceManager.GetString("FurnishingTimerPage_Toolbar_SpeedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parametric Transformer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Gadget_Type_ParametricTransformer {
            get {
                return ResourceManager.GetString("Gadget_Type_ParametricTransformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Portable Waypoint과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Gadget_Type_PortableWaypoint {
            get {
                return ResourceManager.GetString("Gadget_Type_PortableWaypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cooldown end과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GadgetTimerPage_ResetComplete {
            get {
                return ResourceManager.GetString("GadgetTimerPage_ResetComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gadget과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GadgetTimerPage_Title {
            get {
                return ResourceManager.GetString("GadgetTimerPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jade Field과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Gardening_JadeField {
            get {
                return ResourceManager.GetString("Gardening_JadeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Luxuriant Glebe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Gardening_LuxuriantGlebe {
            get {
                return ResourceManager.GetString("Gardening_LuxuriantGlebe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Orderly Meadow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Gardening_OrderlyMeadow {
            get {
                return ResourceManager.GetString("Gardening_OrderlyMeadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GardeningItemTimer_Complete {
            get {
                return ResourceManager.GetString("GardeningItemTimer_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gardening과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GardeningTimerPage_Title {
            get {
                return ResourceManager.GetString("GardeningTimerPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (None)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GatheringItem_ItemNote_None {
            get {
                return ResourceManager.GetString("GatheringItem_ItemNote_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amethyst Lump과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GatheringItem_Type_AmethystLump {
            get {
                return ResourceManager.GetString("GatheringItem_Type_AmethystLump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artifact과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GatheringItem_Type_Artifact {
            get {
                return ResourceManager.GetString("GatheringItem_Type_Artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artifact 12H과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GatheringItem_Type_Artifact12H {
            get {
                return ResourceManager.GetString("GatheringItem_Type_Artifact12H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chunk과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GatheringItem_Type_Chunk {
            get {
                return ResourceManager.GetString("GatheringItem_Type_Chunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crystal Chunk과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GatheringItem_Type_CrystalChunk {
            get {
                return ResourceManager.GetString("GatheringItem_Type_CrystalChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crystal Core과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GatheringItem_Type_CrystalCore {
            get {
                return ResourceManager.GetString("GatheringItem_Type_CrystalCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Electro Crystal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GatheringItem_Type_ElectroCrystal {
            get {
                return ResourceManager.GetString("GatheringItem_Type_ElectroCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Iron Chunk과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GatheringItem_Type_IronChunk {
            get {
                return ResourceManager.GetString("GatheringItem_Type_IronChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magical Crystal Chunk과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GatheringItem_Type_MagicalCrystalChunk {
            get {
                return ResourceManager.GetString("GatheringItem_Type_MagicalCrystalChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specialty과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GatheringItem_Type_Specialty {
            get {
                return ResourceManager.GetString("GatheringItem_Type_Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   White Iron Chunk과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GatheringItem_Type_WhiteIronChunk {
            get {
                return ResourceManager.GetString("GatheringItem_Type_WhiteIronChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GatheringItemMain_Title {
            get {
                return ResourceManager.GetString("GatheringItemMain_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restored과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GatheringItemTimer_ResetComplete {
            get {
                return ResourceManager.GetString("GatheringItemTimer_ResetComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remain과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GatheringItemTimerPage_Remain {
            get {
                return ResourceManager.GetString("GatheringItemTimerPage_Remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expedition Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_Expedition {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expedition Timer show each expedition&apos;s remain time &amp; expected end time. You can Add / Modify / Remove / Reset expedition item with top toolbar.
        ///Expedition Timer allow up to 5 items.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_Expedition_1 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_Expedition_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This page allow edit expedition item for adding or editing. 
        ///Select expedition type &amp; time and time buff optioin.
        ///For finish editing, click top-right apply button.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_Expedition_2 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_Expedition_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Furnishing Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_Furnishing {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_Furnishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Furnishing Timer show each furnishing complete time remaining &amp; expected complete time. You can Add / Modify / Remove / Reset furnishing item with top toolbar.
        ///Furnishing Timer allow up to 5 items.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_Furnishing_1 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_Furnishing_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This page allow edit furnishing item for adding or editing. 
        ///Select furnishing item rank and enter a note. Note is optional.
        ///For finish editing, click top-right apply button.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_Furnishing_2 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_Furnishing_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gadget Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_Gadget {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_Gadget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gadget Timer show each gadget&apos;s time remaining until reuse &amp; expected reusable time. You can Add / Modify / Remove / Reset gadget item with top toolbar.
        ///Gadget Timer allow up to 500 items.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_Gadget_1 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_Gadget_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This page allow edit gadget item for adding or editing. 
        ///Select gadget type and enter a note. Note is optional.
        ///For finish editing, click top-right apply button.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_Gadget_2 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_Gadget_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gathering Item Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_GatheringItem {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_GatheringItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gathering Item Timer show each collectable item&apos;s recovery time remaining &amp; expected recovery time. You can Add / Modify / Remove / Reset gathering item with top toolbar.
        ///Gathering Item Timer allow up to 500 items.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_GatheringItem_1 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_GatheringItem_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This page allow edit gathering item for adding or editing. 
        ///Select gathering item type and enter a note. Note is optional.
        ///For finish editing, click top-right apply button.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_GatheringItem_2 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_GatheringItem_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm Currency Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_RealmCurrency {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_RealmCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm Currency Timer screen show current RC count &amp; fully restore expected time and etc. Also, you can perform quick edit with bottom buttons.
        ///However, the exact time is not shown in In-game, so there may be a difference.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_RealmCurrency_1 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_RealmCurrency_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm Currency Timer can be set recovery rate and maximum size by setting Realm Rank and Trust Rank. You can adjust it according to your Realm environment.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_RealmCurrency_2 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_RealmCurrency_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm Currency Timer also customize notification. You can set the RC ratio to receive notifications.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_RealmCurrency_3 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_RealmCurrency_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_Resin {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_Resin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin Timer screen show current resin &amp; fully restore expected time and etc. Also, you can perform quick calculation with bottom buttons.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_Resin_1 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_Resin_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin Timer contains bottom buttons to calculate resin.
        ///Press buttons which you want to calculation.
        ///&lt;10, &lt;20, &lt;40 Buttons perform calculation less than 10, 20, 40 respectively.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_Resin_2 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_Resin_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Q.E. button allows user to adjust the number of resins without touching the time.
        ///It is very useful if there is a large difference in the number of resin in the in-game or if the result is not calculated quickly.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_Resin_3 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_Resin_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin Timer also customize notification. You can set the resin count to receive notifications.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_Resin_4 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_Resin_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Talent Book과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_TalentBook {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_TalentBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Talent Book Timer show talent book item which you can get now. This timer reference game server and device timezone.
        ///You can select location with top toolbar. Also, you can see characters who use talent book with bottom button.
        ///This timer does not currently support notifications.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_TalentBook_1 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_TalentBook_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weapon Asc.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_WeaponAscension {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_WeaponAscension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weapon Ascension Timer show weapon ascension item which you can get now. This timer reference game server and device timezone.
        ///You can select location with top toolbar. 
        ///This timer does not currently support notifications.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Timer_WeaponAscension_1 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Timer_WeaponAscension_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin Widget과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Widget_Resin {
            get {
                return ResourceManager.GetString("HowToUse_Category_Widget_Resin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin Widget show now resin &amp; expected fully restore time.
        ///You can run app by touching resin icon. Also, you can refresh resin status by touching layout except resin icon.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Widget_Resin_1 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Widget_Resin_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin Widget support simple layout widget. Simple Widget only show now resin.
        ///You can run app by touching resin icon. Also, you can refresh resin status by touching layout except resin icon.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Widget_Resin_2 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Widget_Resin_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TBook Widget과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Widget_TalentBook {
            get {
                return ResourceManager.GetString("HowToUse_Category_Widget_TalentBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Talent Book Widget show talent book which you can acquire on each location.
        ///Bottom buttons can change location. Also, you can see characters who use talent book by touching talent book image.
        ///You can refresh talent book status by touching layout except buttons and talent book image.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Widget_TalentBook_1 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Widget_TalentBook_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WA Widget과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Widget_WeaponAscension {
            get {
                return ResourceManager.GetString("HowToUse_Category_Widget_WeaponAscension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weapon Ascension Widget show weapon ascension material which you can acquire on each location.
        ///Bottom buttons can change location.
        ///You can refresh weapon ascension material status by touching layout except buttons and material image.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUse_Category_Widget_WeaponAscension_1 {
            get {
                return ResourceManager.GetString("HowToUse_Category_Widget_WeaponAscension_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How To Use과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUsePage_Title {
            get {
                return ResourceManager.GetString("HowToUsePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HowToUseViewerPage_PreTitle {
            get {
                return ResourceManager.GetString("HowToUseViewerPage_PreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InfoPage_AppName {
            get {
                return ResourceManager.GetString("InfoPage_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developer Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InfoPage_DeveloperInfoLabel {
            get {
                return ResourceManager.GetString("InfoPage_DeveloperInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dev Home과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InfoPage_DevHomeButtonText {
            get {
                return ResourceManager.GetString("InfoPage_DevHomeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Github과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InfoPage_GithubButtonText {
            get {
                return ResourceManager.GetString("InfoPage_GithubButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenSource License과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InfoPage_OpenSourceLicenseButtonText {
            get {
                return ResourceManager.GetString("InfoPage_OpenSourceLicenseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InfoPage_Title {
            get {
                return ResourceManager.GetString("InfoPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toast.iOS
        ///Syncfusion.Licensing
        ///Syncfusion.Xamarin.SfGauge
        ///Syncfusion.Xamarin.SfNumericUpDown
        ///Xamarin.Essentials
        ///Newton.Json
        ///Rg.Plugins.Popup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LibraryList {
            get {
                return ResourceManager.GetString("LibraryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Source License과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LicensePage_Title {
            get {
                return ResourceManager.GetString("LicensePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIT License - Andrius Kirilovas
        ///Syncfusion License
        ///Syncfusion License
        ///Syncfusion License
        ///MIT License - Microsoft Corporation
        ///MIT License - James Newton-King
        ///MIT License과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LicenseTypeList {
            get {
                return ResourceManager.GetString("LicenseTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ListTimer_EditTime {
            get {
                return ResourceManager.GetString("ListTimer_EditTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timer count is maximum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ListTimer_LimitExceed {
            get {
                return ResourceManager.GetString("ListTimer_LimitExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scheduled D/T of full recovery과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainPage_EndDateTimeTitle {
            get {
                return ResourceManager.GetString("MainPage_EndDateTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last Input D/T과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainPage_LastInputDateTimeTitle {
            get {
                return ResourceManager.GetString("MainPage_LastInputDateTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hold button during 0.5s to apply calc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainPage_QuickCalcButton_Toast {
            get {
                return ResourceManager.GetString("MainPage_QuickCalcButton_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Until full recovery과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainPage_RemainTimeLabel {
            get {
                return ResourceManager.GetString("MainPage_RemainTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MasterDetail_MasterList_AppInfo {
            get {
                return ResourceManager.GetString("MasterDetail_MasterList_AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daily Check-In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MasterDetail_MasterList_Event_DailyCheckIn {
            get {
                return ResourceManager.GetString("MasterDetail_MasterList_Event_DailyCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expedition과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MasterDetail_MasterList_Expedition {
            get {
                return ResourceManager.GetString("MasterDetail_MasterList_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Furnishing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MasterDetail_MasterList_Furnishing {
            get {
                return ResourceManager.GetString("MasterDetail_MasterList_Furnishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gadget과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MasterDetail_MasterList_Gadget {
            get {
                return ResourceManager.GetString("MasterDetail_MasterList_Gadget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gardening과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MasterDetail_MasterList_Gardening {
            get {
                return ResourceManager.GetString("MasterDetail_MasterList_Gardening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gathering Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MasterDetail_MasterList_GatheringItem {
            get {
                return ResourceManager.GetString("MasterDetail_MasterList_GatheringItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How To Use과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MasterDetail_MasterList_HowToUse {
            get {
                return ResourceManager.GetString("MasterDetail_MasterList_HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm Currency과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MasterDetail_MasterList_RealmCurrency {
            get {
                return ResourceManager.GetString("MasterDetail_MasterList_RealmCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm Friendship과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MasterDetail_MasterList_RealmFriendship {
            get {
                return ResourceManager.GetString("MasterDetail_MasterList_RealmFriendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MasterDetail_MasterList_Resin {
            get {
                return ResourceManager.GetString("MasterDetail_MasterList_Resin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MasterDetail_MasterList_Settings {
            get {
                return ResourceManager.GetString("MasterDetail_MasterList_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Talent Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MasterDetail_MasterList_Talent {
            get {
                return ResourceManager.GetString("MasterDetail_MasterList_Talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weapon Asc.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MasterDetail_MasterList_WeaponAscension {
            get {
                return ResourceManager.GetString("MasterDetail_MasterList_WeaponAscension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   World Map과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MasterDetail_MasterList_Web_GenshinWorldMap {
            get {
                return ResourceManager.GetString("MasterDetail_MasterList_Web_GenshinWorldMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   expedition is complete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_Expedition_Message {
            get {
                return ResourceManager.GetString("Noti_Expedition_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expedition Complete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_Expedition_Title {
            get {
                return ResourceManager.GetString("Noti_Expedition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   complete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_Furnishing_Message {
            get {
                return ResourceManager.GetString("Noti_Furnishing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Furnishing Complete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_Furnishing_Title {
            get {
                return ResourceManager.GetString("Noti_Furnishing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is usable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_Gadget_Message {
            get {
                return ResourceManager.GetString("Noti_Gadget_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gadget Noti과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_Gadget_Title {
            get {
                return ResourceManager.GetString("Noti_Gadget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   gardening is complete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_Gardening_Message {
            get {
                return ResourceManager.GetString("Noti_Gardening_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gardening Complete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_Gardening_Title {
            get {
                return ResourceManager.GetString("Noti_Gardening_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   are restored now과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_GatheringItem_Message {
            get {
                return ResourceManager.GetString("Noti_GatheringItem_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore Gathering Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_GatheringItem_Title {
            get {
                return ResourceManager.GetString("Noti_GatheringItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timer Reset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_QuickAction_ResetTimer {
            get {
                return ResourceManager.GetString("Noti_QuickAction_ResetTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run Genshin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_QuickAction_RunGenshinApp {
            get {
                return ResourceManager.GetString("Noti_QuickAction_RunGenshinApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   charge is complete.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_RealmCurrency_Message {
            get {
                return ResourceManager.GetString("Noti_RealmCurrency_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm Currency Noti과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_RealmCurrency_Title {
            get {
                return ResourceManager.GetString("Noti_RealmCurrency_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   charge is complete.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_RealmFriendship_Message {
            get {
                return ResourceManager.GetString("Noti_RealmFriendship_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm Friendship Bounty Noti과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Noti_RealmFriendship_Title {
            get {
                return ResourceManager.GetString("Noti_RealmFriendship_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the number of resins you would like to be notified of.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotiSettingPage_AddDialog_Summary {
            get {
                return ResourceManager.GetString("NotiSettingPage_AddDialog_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Noti Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotiSettingPage_AddDialog_Title {
            get {
                return ResourceManager.GetString("NotiSettingPage_AddDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The item already exists and will not be added.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotiSettingPage_AlreadyExistToast_Message {
            get {
                return ResourceManager.GetString("NotiSettingPage_AlreadyExistToast_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At least one item must exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotiSettingPage_CannotRemoveToast_Message {
            get {
                return ResourceManager.GetString("NotiSettingPage_CannotRemoveToast_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expected noti time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotiSettingPage_List_ExpectedNotiTime {
            get {
                return ResourceManager.GetString("NotiSettingPage_List_ExpectedNotiTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter only the number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotiSettingPage_NotIntegerDialog_Summary {
            get {
                return ResourceManager.GetString("NotiSettingPage_NotIntegerDialog_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format mismatch과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotiSettingPage_NotIntegerDialog_Title {
            get {
                return ResourceManager.GetString("NotiSettingPage_NotIntegerDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No selected item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotiSettingPage_NotSelectedToast_Message {
            get {
                return ResourceManager.GetString("NotiSettingPage_NotSelectedToast_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a number in scope과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotiSettingPage_OutOfRangeDialog_Summary {
            get {
                return ResourceManager.GetString("NotiSettingPage_OutOfRangeDialog_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input value out of range과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotiSettingPage_OutOfRangeDialog_Title {
            get {
                return ResourceManager.GetString("NotiSettingPage_OutOfRangeDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Noti Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotiSettingPage_Title {
            get {
                return ResourceManager.GetString("NotiSettingPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   have been recovered과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotiText {
            get {
                return ResourceManager.GetString("NotiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recovery Resin Notification과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotiTitle {
            get {
                return ResourceManager.GetString("NotiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now Location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NowLocation_PreLabel {
            get {
                return ResourceManager.GetString("NowLocation_PreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NowServer_PreLabel {
            get {
                return ResourceManager.GetString("NowServer_PreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now Region UTC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NowUTC_PreLabel {
            get {
                return ResourceManager.GetString("NowUTC_PreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overflow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Overflow_Text {
            get {
                return ResourceManager.GetString("Overflow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bare-Bones과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Realm_Rank_1 {
            get {
                return ResourceManager.GetString("Realm_Rank_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit for a King과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Realm_Rank_10 {
            get {
                return ResourceManager.GetString("Realm_Rank_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Humble Abode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Realm_Rank_2 {
            get {
                return ResourceManager.GetString("Realm_Rank_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cozy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Realm_Rank_3 {
            get {
                return ResourceManager.GetString("Realm_Rank_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Queen-Size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Realm_Rank_4 {
            get {
                return ResourceManager.GetString("Realm_Rank_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elegant과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Realm_Rank_5 {
            get {
                return ResourceManager.GetString("Realm_Rank_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exquisite과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Realm_Rank_6 {
            get {
                return ResourceManager.GetString("Realm_Rank_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extraordinary과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Realm_Rank_7 {
            get {
                return ResourceManager.GetString("Realm_Rank_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stately과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Realm_Rank_8 {
            get {
                return ResourceManager.GetString("Realm_Rank_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Luxury과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Realm_Rank_9 {
            get {
                return ResourceManager.GetString("Realm_Rank_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now Currency과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RealmCurrency_NowCurrency {
            get {
                return ResourceManager.GetString("RealmCurrency_NowCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm Rank과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RealmCurrency_RealmRank {
            get {
                return ResourceManager.GetString("RealmCurrency_RealmRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Until the coins are full과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RealmCurrency_RemainTimeLabel {
            get {
                return ResourceManager.GetString("RealmCurrency_RemainTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trust Rank과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RealmCurrency_TrustRank {
            get {
                return ResourceManager.GetString("RealmCurrency_TrustRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the number of currency ratio you would like to be notified of.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RealmCurrencyNotiSettingPage_AddDialog_Summary {
            get {
                return ResourceManager.GetString("RealmCurrencyNotiSettingPage_AddDialog_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Noti Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RealmCurrencyNotiSettingPage_AddDialog_Title {
            get {
                return ResourceManager.GetString("RealmCurrencyNotiSettingPage_AddDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can occur difference between input and server time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RealmCurrencyTimerPage_Caution {
            get {
                return ResourceManager.GetString("RealmCurrencyTimerPage_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Until gifts are full과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RealmFriendship_RemainTimeLabel {
            get {
                return ResourceManager.GetString("RealmFriendship_RemainTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simple Edit Resin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResinSimpleEditDialog_Title {
            get {
                return ResourceManager.GetString("ResinSimpleEditDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renew your account information or try to enable real-time note on the account sync status screen.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResinTimerPage_SyncTip {
            get {
                return ResourceManager.GetString("ResinTimerPage_SyncTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin Widget과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResinWidget_Name {
            get {
                return ResourceManager.GetString("ResinWidget_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Resin Widget Complete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResinWidget_UpdateComplete {
            get {
                return ResourceManager.GetString("ResinWidget_UpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_App_AccountSync_Connected {
            get {
                return ResourceManager.GetString("SettingPage_Section_App_AccountSync_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Connected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_App_AccountSync_NotConnected {
            get {
                return ResourceManager.GetString("SettingPage_Section_App_AccountSync_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account Sync과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_App_AccountSync_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_App_AccountSync_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_App_AppLang_Dialog_Default {
            get {
                return ResourceManager.GetString("SettingPage_Section_App_AppLang_Dialog_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select App Lang과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_App_AppLang_Dialog_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_App_AppLang_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_App_AppLang_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_App_AppLang_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Notification과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_App_Cell_Notification_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_App_Cell_Notification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_App_InGameServer_Dialog_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_App_InGameServer_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_App_InGameServer_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_App_InGameServer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set menus visibility과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_App_SelectVisibleMenu_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_App_SelectVisibleMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Start Screen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_App_Start_DetailScreen_Dialog_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_App_Start_DetailScreen_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Screen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_App_Start_DetailScreen_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_App_Start_DetailScreen_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_App_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use 24H Time Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_App_Use24HTimeFormat_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_App_Use24HTimeFormat_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_Main_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resin Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_ResinTimer_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_ResinTimer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Quick Calc Vibration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_TimerCommon_QuickCalcVibrate_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_TimerCommon_QuickCalcVibrate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Overflow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_TimerCommon_ShowOverflow_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_TimerCommon_ShowOverflow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_TimerCommon_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_TimerCommon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run App When Touch과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_Widget_RootTouch_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_Widget_RootTouch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Widget과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Section_Widget_Title {
            get {
                return ResourceManager.GetString("SettingPage_Section_Widget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingPage_Title {
            get {
                return ResourceManager.GetString("SettingPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync Fail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Sync_Fail {
            get {
                return ResourceManager.GetString("Sync_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renew과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Sync_Renew {
            get {
                return ResourceManager.GetString("Sync_Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync Success과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Sync_Success {
            get {
                return ResourceManager.GetString("Sync_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Working...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Sync_Working {
            get {
                return ResourceManager.GetString("Sync_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply Characters과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TalentCharacterPage_Title {
            get {
                return ResourceManager.GetString("TalentCharacterPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now Talent Book과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TalentTimerPage_NowBook_PreLabel {
            get {
                return ResourceManager.GetString("TalentTimerPage_NowBook_PreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All books available과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TalentTimerPage_NowBook_PreLabel_All {
            get {
                return ResourceManager.GetString("TalentTimerPage_NowBook_PreLabel_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now Location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TalentTimerPage_NowLocation_PreLabel {
            get {
                return ResourceManager.GetString("TalentTimerPage_NowLocation_PreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TalentTimerPage_NowServer_PreLabel {
            get {
                return ResourceManager.GetString("TalentTimerPage_NowServer_PreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now Region UTC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TalentTimerPage_NowUTC_PreLabel {
            get {
                return ResourceManager.GetString("TalentTimerPage_NowUTC_PreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TalentTimerPage_SelectLocationDialog_Title {
            get {
                return ResourceManager.GetString("TalentTimerPage_SelectLocationDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply Characters과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TalentTimerPage_TalentCharacterButton_Text {
            get {
                return ResourceManager.GetString("TalentTimerPage_TalentCharacterButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Talent Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TalentTimerPage_Title {
            get {
                return ResourceManager.GetString("TalentTimerPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today T-Book과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TalentWidget_Title {
            get {
                return ResourceManager.GetString("TalentWidget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Talent Widget Updated과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TalentWidget_UpdateComplete {
            get {
                return ResourceManager.GetString("TalentWidget_UpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Toolbar_Add {
            get {
                return ResourceManager.GetString("Toolbar_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Toolbar_Apply {
            get {
                return ResourceManager.GetString("Toolbar_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Toolbar_Edit {
            get {
                return ResourceManager.GetString("Toolbar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Toolbar_EditTime {
            get {
                return ResourceManager.GetString("Toolbar_EditTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Toolbar_Remove {
            get {
                return ResourceManager.GetString("Toolbar_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Toolbar_Reset {
            get {
                return ResourceManager.GetString("Toolbar_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Toolbar_ResetAll {
            get {
                return ResourceManager.GetString("Toolbar_ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input correct value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValueEdit_ValueError_Message {
            get {
                return ResourceManager.GetString("ValueEdit_ValueError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today Weapon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WAWidget_Title {
            get {
                return ResourceManager.GetString("WAWidget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WA Widget Updated과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WAWidget_UpdateComplete {
            get {
                return ResourceManager.GetString("WAWidget_UpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now W.A. Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WeaponAscensionTimerPage_NowWA_PreLabel {
            get {
                return ResourceManager.GetString("WeaponAscensionTimerPage_NowWA_PreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All W.A. Items available과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WeaponAscensionTimerPage_NowWA_PreLabel_All {
            get {
                return ResourceManager.GetString("WeaponAscensionTimerPage_NowWA_PreLabel_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weapon Asc.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WeaponAscensionTimerPage_Title {
            get {
                return ResourceManager.GetString("WeaponAscensionTimerPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configure Widget과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WidgetConfigure_Title {
            get {
                return ResourceManager.GetString("WidgetConfigure_Title", resourceCulture);
            }
        }
    }
}
